### ISSUE TITLE
Project help link is broken

### ISSUE THREAD

**Issue by suryasaha** [solgenomics/cgen#21]
![image](https://user-images.githubusercontent.com/1084749/107985191-9b3ad100-6f97-11eb-8421-64303dd07891.png)

**Comment by suryasaha** [comment]
This is how its set up for tomato
http://tea.solgenomics.net/anatomy_viewer/microscopy
But we can do it in a different way if it makes more sense for CGEN data

**Comment by MFlores2021** [comment]
Close #b056dd8
